### ISSUE TITLE
common textures mixed with level editor support files

### ISSUE THREAD

**Issue by illwieckz** [PadWorld-Entertainment/wop-mapeditor-support#1]
Hi, I noticed the repository was not only storing the support files for NetRadiant level editor, but also the common textures (and also sample maps). One problem is that those extra files (from `wop` folder) are downloaded by the NetRadiant build process without making any use of them. Another problem is that the level editor support files are expected to configure the level editor for a given game but not do that much.

A recommended good practice is to make a repository for the level editor support, and another repository for common files, this other repository being recommended to be distributed as pk3 with the game itself.

I have seen you're going to make a new release of World Of Padman soon, so since you have full control on the game to ship those common files with the game itself, it may be a good idea to do things that way.

For example, Unvanquished does things this way:

- a repository for level editor support files: https://github.com/Unvanquished/unvanquished-mapeditor-support
- a repository for common files: https://github.com/UnvanquishedAssets/tex-common_src.dpkdir (which is distributed with the game as `tex-common_2.2.dpk`), dpk being a variant of pk3 the method is the same.

For map samples, some may prefer to have a separate repository dedicated to them (because maps are heavy and are not expected to contribute to other maps unlike common shaders), but in all case map samples better be distributed in common pk3 or another pk3 than with level editor support files.

**Comment by kai-li-wop** [comment]
Hi @illwieckz, thank you for your feedback. I assumed that it was no problem to store further files in this repository. I had understood your NetRadiant process in such a way that only files from the Netradiant directory are referenced by you and processed accordingly. In this respect, I thought I could store other support files, e.g. for other editors, in parallel in their own directories. That's why I didn't think there was a problem with the wop directory, which now also contains the demo maps and prefabs for the different game modes in addition to the common textures. I can imagine putting common textures and demo maps (bsp) in a pk3 and distributing them directly with the game, even if it is not really necessary for playing. My idea here was originally to keep the game clean and only distribute the files you need to play. With the prefabs in map format it becomes more difficult now, as these should not be part of a PK3 file.

Apart from that, I don't really understand this sentence: "Another problem is that the level editor support files are expected to configure the level editor for a given game but not do that much." Does this mean that the files do not configure NetRadiant correctly on our part? Is there something missing? For me everything always worked and I could start directly with these files for WoP with the NetRadiant to create maps. What files do you think should be stored there so that NetRadiant can be configured correctly for WoP?

**Comment by kai-li-wop** [comment]
@illwieckz: I removed the files from the map editor support repo like asked.
